name: Tests

on:
    push:
        branches: [main]
    pull_request:

env:
    NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
    BIOGRID_API_KEY: ${{ secrets.BIOGRID_API_KEY }}
    AWS_ID: ${{ secrets.AWS_ID }}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.9', '3.10']
        
        steps:
          - uses: actions/checkout@v4

          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}
            
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pipx
                pipx install poetry
                poetry install --no-interaction --with test --with-override
                poetry install --no-interaction --with dev --with-override
            
          - name: Test with pytest
            run: poetry run pytest
          - name: Type check with mypy
            run: poetry run mypy
          - name: Lint with flake8
            run: |
                poetry run flake8 src/data/*
                poetry run flake8 src/features/*
                poetry run flake8 tests
